### PR TITLE
cleanup vint implementation

### PR DESCRIPTION
**Pull request by hendrikmuhs**
cleanup vint implementation, improve vint length performance

### CODE REVIEW

**Comment by narekgharibyan** [comment]
Nice!

**Comment by narekgharibyan** [comment]
Btw, seems more and more libs are supporting M1 chip, chances are I'll switch to M1 sometime soon, so can work on making it compatible with M1 🤞

**Comment by hendrikmuhs** [comment]
> Btw, seems more and more libs are supporting M1 chip, chances are I'll switch to M1 sometime soon, so can work on making it compatible with M1 crossed_fingers

It already works for arm, so I don't expect a lot of problems for M1. What would be nice however:

 - continuous integration, the last time I checked github does not support it. Some 3rdparties have it.
 - the code has some significant optimizations for intel processors (intrinsics). Arm has similar intrinsics, but as support isn't implemented yet, the code uses fallbacks. They are are significantly slower. This applies e.g. to fuzzy matching, but also for dictionary creation.

**Comment by narekgharibyan** [comment]
Yup, I'll try to compile it when I get M1, and we can take it from there.

**Pull request merged**
