### PR TITLE
Add support for Python 3.11

### PR DESCRIPTION
**Pull request by y3ti**
Changes:

* fix the URL to zlib
* add python 3.11 to the build scripts and GHA workflows

May we ask for a new release for Python 3.11? :)

### CODE REVIEW

**Comment by y3ti** [comment]
It seems that the issue with building on macOS is similar to this one: https://github.com/actions/setup-python/issues/577

**Comment by hendrikmuhs** [comment]
@y3ti Thanks for the PR. Is it ok for you to wait for https://github.com/actions/setup-python/issues/577 until we proceed with this?

**Comment by y3ti** [comment]
@hendrikmuhs Yes, it's okay. Thank you for the information! :)

**Comment by hendrikmuhs** [comment]
superseded by #264

**Pull request closed without merging**
