### PR TITLE
Add new python versions - part 1

### PR DESCRIPTION
**Pull request by narekgharibyan**
This PR adds new python versions on ubuntu builder.
I'll make a follow-up PR, which will drop old versions, after this PR is merged and dockerhub is updated.

On OS X we are installing python during travis run, so I made those updates in this PR.

### CODE REVIEW

**Comment by hendrikmuhs** [comment]
Sounds good, I am not sure what is wrong with osx, this might be due to the Travis Billing changes: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by narekgharibyan** [comment]
So I think we can merge this and let dockerhub build new images. So I can create second PR.
Coverage is fine too.

I have already reverted OS X changes. 

Wdyt ?

**Review by hendrikmuhs — APPROVED** [review]
LGTM

Lets merge it and wait for an answer from travis support.

Before any new PR I suggest to disable the mac builds until we have a solution.

**Comment by narekgharibyan** [comment]
Disabled Mac builds.

**Pull request merged**
